# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import match_events_pb2 as match__events__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in match_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchEventsServiceStub(object):
    """─── Match Events Service ────────────────────────────────────────────────
    gRPC streaming for B2B clients (Viaplay, TV2)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.unary_stream(
                '/viovision.v1.MatchEventsService/StreamEvents',
                request_serializer=match__events__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=match__events__pb2.MatchFrame.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/viovision.v1.MatchEventsService/ListSessions',
                request_serializer=match__events__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=match__events__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetSessionEvents = channel.unary_stream(
                '/viovision.v1.MatchEventsService/GetSessionEvents',
                request_serializer=match__events__pb2.GetSessionEventsRequest.SerializeToString,
                response_deserializer=match__events__pb2.MatchFrame.FromString,
                _registered_method=True)


class MatchEventsServiceServicer(object):
    """─── Match Events Service ────────────────────────────────────────────────
    gRPC streaming for B2B clients (Viaplay, TV2)
    """

    def StreamEvents(self, request, context):
        """Stream events for an active match session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List past sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionEvents(self, request, context):
        """Get historical events for a completed session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchEventsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=match__events__pb2.StreamEventsRequest.FromString,
                    response_serializer=match__events__pb2.MatchFrame.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=match__events__pb2.ListSessionsRequest.FromString,
                    response_serializer=match__events__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetSessionEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSessionEvents,
                    request_deserializer=match__events__pb2.GetSessionEventsRequest.FromString,
                    response_serializer=match__events__pb2.MatchFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viovision.v1.MatchEventsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('viovision.v1.MatchEventsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchEventsService(object):
    """─── Match Events Service ────────────────────────────────────────────────
    gRPC streaming for B2B clients (Viaplay, TV2)
    """

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/viovision.v1.MatchEventsService/StreamEvents',
            match__events__pb2.StreamEventsRequest.SerializeToString,
            match__events__pb2.MatchFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/viovision.v1.MatchEventsService/ListSessions',
            match__events__pb2.ListSessionsRequest.SerializeToString,
            match__events__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/viovision.v1.MatchEventsService/GetSessionEvents',
            match__events__pb2.GetSessionEventsRequest.SerializeToString,
            match__events__pb2.MatchFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
